title: Stitch-sync
description: Automatically convert embroidery files and copy them to USB drives
theme: jekyll-theme-tactile
markdown: kramdown

# Set default layout for all pages
defaults:
  -
    scope:
      path: "" # Apply to all files
      type: "pages"
    values:
      layout: "default"

# Navigation structure
navigation:
  - title: Home
    url: /
  - title: Documentation
    items:
      - title: Specification
        url: /docs/spec
      - title: Commands
        url: /docs/commands
      - title: Developer Notes
        url: /docs/developer-notes
